name: education_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  file_picker: ^6.1.1
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.5
  url_launcher: ^6.2.2
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
